In [53]:
import torch
import torch.nn as nn

 Within the nn package, there is a class called Module, and it is the base class for all of neural network modules which includes layers.

This means that all of the layers in PyTorch extend the nn.Module class and inherit all of PyTorch’s built-in functionality within the nn.Module class. In OOP this concept is known as inheritance.

## PyTorch nn.Modules Have A forward() Method
When we pass a tensor to our network as input, the tensor flows forward though each layer transformation until the tensor reaches the output layer. This process of a tensor flowing forward though the network is known as a forward pass.

## Extending PyTorch’s nn.Module Class

In [31]:
class Network:
    def __init__(self):
        self.layer = None

    def forward(self, t):
        t = self.layer(t)
        return t

This is a good start, but the class hasn’t yet extended the nn.Module class. To make our Network class extend nn.Module, we must do two additional things:

Specify the nn.Module class in parentheses on line 1.

Insert a call to the super class constructor on line 3 inside the constructor.

In [32]:
class Network(nn.Module):
    def __init__(self):
        super.__init__()
        self.layer = None

    def forward(self, t):
        t = self.layer(t)
        return t

## Define The Network’s Layers As Class Attributes

In [33]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

        self.fc1 = nn.Linear(in_features=12 * 4 * 4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)

    def forward(self, t):
        # implement the forward pass
        return t

## Learnable Parameters

In [34]:
network = Network()

In [35]:
print(network)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


### Accessing the nework's layers

In [36]:
network.conv1

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [37]:
network.conv2

Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))

In [38]:
network.fc1

Linear(in_features=192, out_features=120, bias=True)

In [39]:
network.fc2

Linear(in_features=120, out_features=60, bias=True)

In [40]:
network.out

Linear(in_features=60, out_features=10, bias=True)

### Accessing the network's weights

In [41]:
network.conv1.weight

Parameter containing:
tensor([[[[-0.0374, -0.0057,  0.0686, -0.0151, -0.0176],
          [ 0.0615,  0.0114, -0.0220,  0.1018,  0.0447],
          [-0.0231, -0.0570, -0.0282,  0.0211,  0.1473],
          [ 0.1763,  0.0177,  0.0668,  0.0246, -0.0313],
          [-0.0519, -0.0314, -0.0726,  0.1313, -0.1207]]],


        [[[ 0.0397,  0.0847,  0.0503, -0.0881, -0.0531],
          [ 0.0080, -0.1177, -0.0783,  0.1364,  0.0947],
          [-0.1492,  0.0201, -0.1387, -0.0095, -0.0943],
          [ 0.0451,  0.0168,  0.0343, -0.1041,  0.1467],
          [ 0.1014,  0.0680, -0.1002, -0.0527, -0.1891]]],


        [[[ 0.0880,  0.0625, -0.1450, -0.1764,  0.0420],
          [-0.1575,  0.1253,  0.0617, -0.0449, -0.1536],
          [-0.1943,  0.1444, -0.0441,  0.0760,  0.0909],
          [ 0.0083,  0.1179,  0.1655, -0.1199, -0.0409],
          [ 0.1530,  0.1078,  0.0820,  0.1670,  0.0361]]],


        [[[ 0.0812,  0.1646,  0.1901,  0.1214, -0.0725],
          [ 0.0764, -0.0805, -0.0777, -0.1130, -0.1209

## Weight tensor shape

### Convolutional Layers

In [42]:
network.conv1

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [43]:
network.conv1.weight.shape

torch.Size([6, 1, 5, 5])

In [44]:
network.conv2

Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))

In [45]:
network.conv2.weight.shape

torch.Size([12, 6, 5, 5])

Our tensors are rank-4 tensors. The first axis represents the number of filters. The second axis represents the depth of each filter which corresponds to the number of input channels being convolved.

The last two axes represent the height and width of each filter. We can pull out any single filter by indexing into the weight tensor’s first axis.

### Linear Layers

In [46]:
network.fc1

Linear(in_features=192, out_features=120, bias=True)

In [47]:
network.fc1.weight.shape

torch.Size([120, 192])

In [48]:
network.fc2

Linear(in_features=120, out_features=60, bias=True)

In [49]:
network.fc2.weight.shape

torch.Size([60, 120])

## Accessing the network parameters

In [50]:
for name, param in network.named_parameters():
    print(name, '\t\t', param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])


## Transform using a Matrix

In [54]:
in_features = torch.tensor([1,2,3,4], dtype=torch.float32)

weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
], dtype=torch.float32)

weight_matrix.matmul(in_features)

tensor([30., 40., 50.])

## Transform using a pytorch linear layer

In [55]:
fc = nn.Linear(in_features=4, out_features=3, bias=False)

In [61]:
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)

In [62]:
fc.weight = nn.Parameter(weight_matrix)

In [63]:
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)

In [60]:
fc = nn.Linear(in_features=4, out_features=3, bias=False)
fc.weight = nn.Parameter(weight_matrix)
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)