In [1]:
import torch
import numpy as np

## Reduction operations

### Summations

In [2]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [3]:
t.sum()

tensor(8.)

In [4]:
t.prod()

tensor(0.)

In [5]:
t.mean()

tensor(0.8889)

In [6]:
t.std()

tensor(1.1667)

### Reducing tensors by axes

In [11]:
t = torch.tensor([[
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],[
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4]
]], dtype=torch.float32)

In [19]:
t.sum(dim=0)

tensor([[3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [7., 7., 7., 7.]])

In [20]:
t.sum(dim=1)

tensor([[6., 6., 6., 6.],
        [9., 9., 9., 9.]])

In [21]:
t.sum(dim=2)

tensor([[ 4.,  8., 12.],
        [ 8., 12., 16.]])

### Argmax

In [23]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [24]:
t.max()

tensor(5.)

In [25]:
t.argmax()

tensor(11)