In [1]:
import torch
import numpy as np

## Reduction operations

### Summations

In [2]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [3]:
t.sum()

tensor(8.)

In [4]:
t.prod()

tensor(0.)

In [5]:
t.mean()

tensor(0.8889)

In [6]:
t.std()

tensor(1.1667)

### Reducing tensors by axes

In [11]:
t = torch.tensor([[
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],[
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4]
]], dtype=torch.float32)

In [19]:
t.sum(dim=0)

tensor([[3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [7., 7., 7., 7.]])

In [20]:
t.sum(dim=1)

tensor([[6., 6., 6., 6.],
        [9., 9., 9., 9.]])

In [21]:
t.sum(dim=2)

tensor([[ 4.,  8., 12.],
        [ 8., 12., 16.]])

### Argmax

In [23]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [24]:
t.max()

tensor(5.)

In [25]:
t.argmax()

tensor(11)

In [26]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [27]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [28]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [29]:
t.argmax(dim=1)

tensor([3, 2, 3])

## Accessing elements inside tensors

In [30]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)


In [31]:
t.mean()

tensor(5.)

In [32]:
t.mean().item()

5.0

In [33]:
t.mean(dim=0)

tensor([4., 5., 6.])

In [36]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [ ]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)

## Advanced indexing : https://numpy.org/doc/stable/reference/arrays.indexing.html