In [2]:
import torch
import numpy as np

In [3]:
t2 = torch.tensor ([
    [1,2,3,4,5,6]
])

## Reshaping

In [4]:
t2.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [5]:
t2.reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
t2.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Printing details about torch

In [9]:
print(t2.dtype)
print(t2.device)
print(t2.layout)
print(torch.__version__)

torch.int64
cpu
torch.strided
1.6.0


## Creating Tensors

In [10]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [11]:
o1 = torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)

In [12]:
print(o1)

tensor([1., 2., 3.])


In [13]:
print(o2)

tensor([1, 2, 3])


In [14]:
print(o3)

tensor([1, 2, 3])


In [15]:
print(o4)

tensor([1, 2, 3])


##### Except the first, all three are dtype int

## Sharing vs Copy

In [16]:
print('old:', data)

data[0] = 0

print('new:', data)

print(o1)

print(o2)

print(o3)

print(o4)

old: [1 2 3]
new: [0 2 3]
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 2, 3])
tensor([0, 2, 3])


### Note that the best way to initialise tensors would be .tensor() for normal usage, .as_tensor() for performance tuned usage

## Flatten, Reshape and Squeeze

In [17]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [18]:
t.size()

torch.Size([3, 4])

In [19]:
t.shape

torch.Size([3, 4])

In [20]:
t.numel()

12

### Reshaping

In [21]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [22]:
t.reshape([2,6])


tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [23]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [24]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [25]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [26]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [27]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

### Squeeze and Unsqueeze

In [28]:
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [29]:
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [30]:
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


### Flattening

In [31]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [32]:
t = torch.ones(4, 3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Concatenating

In [34]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

In [35]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [36]:
 torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [37]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [38]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [39]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

## Flatten operation for a batch of images

### Creating the images

In [45]:
t1 = torch.tensor([
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2,2],
    [2,2,2,2,2],
    [2,2,2,2,2],
    [2,2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3,3],
    [3,3,3,3,3],
    [3,3,3,3,3],
    [3,3,3,3,3]
])

In [46]:
t = torch.stack((t1, t2, t3))

In [47]:
print(t.shape)
print(t)

torch.Size([3, 4, 5])
tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]])


In [50]:
t = t.reshape(3,1,4,5)
t

tensor([[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[2, 2, 2, 2, 2],
          [2, 2, 2, 2, 2],
          [2, 2, 2, 2, 2],
          [2, 2, 2, 2, 2]]],


        [[[3, 3, 3, 3, 3],
          [3, 3, 3, 3, 3],
          [3, 3, 3, 3, 3],
          [3, 3, 3, 3, 3]]]])

#### First Image

In [51]:
t[0]

tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]])

#### First color channel in the first image

In [52]:
t[0][0]

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

#### First row of pixels in the first color channel of the image

In [54]:
t[0][0][0]

tensor([1, 1, 1, 1, 1])

#### First pixel value in the first row of the first color channel of the first image.

In [56]:
t[0][0][0][0]

tensor(1)

In [58]:
print(t.reshape(1,-1)[0])
print(t.reshape(-1))
print(t.view(t.numel()))
print(t.flatten())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
