In [17]:
import torch
import numpy as np

In [18]:
t2 = torch.tensor ([
    [1,2,3,4,5,6]
])

## Reshaping

In [19]:
t2.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [20]:
t2.reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
t2.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Printing details about torch

In [22]:
print(t.dtype)
print(t.device)
print(t.layout)
print(torch.__version__)

torch.int64
cpu
torch.strided
1.6.0


## Creating Tensors

In [23]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [24]:
o1 = torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)

In [25]:
print(o1)

tensor([1., 2., 3.])


In [26]:
print(o2)

tensor([1, 2, 3])


In [27]:
print(o3)

tensor([1, 2, 3])


In [28]:
print(o4)

tensor([1, 2, 3])


##### Except the first, all three are dtype int

## Sharing vs Copy

In [31]:
print('old:', data)

data[0] = 0

print('new:', data)

print(o1)

print(o2)

print(o3)

print(o4)

old: [0 2 3]
new: [0 2 3]
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 2, 3])
tensor([0, 2, 3])


### Note that the best way to initialise tensors would be .tensor() for normal usage, .as_tensor() for performance tuned usage

## Flatten, Reshape and Squeeze

In [32]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [34]:
t.size()

torch.Size([3, 4])

In [35]:
t.shape

torch.Size([3, 4])

In [36]:
t.numel()

12

### Reshaping

In [37]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [38]:
t.reshape([2,6])


tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [39]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [40]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [41]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [42]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [44]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

### Squeeze and Unsqueeze

In [46]:
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [47]:
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [48]:
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


### Flattening

In [49]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [52]:
t = torch.ones(4, 3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [53]:
flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Concatenating

In [54]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

In [55]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [56]:
 torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [57]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [58]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [59]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

## Flatten operation for a batch of images

### Creating the images

In [1]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

NameError: name 'torch' is not defined